version: '3'

services:
  loki:
    image: grafana/loki:2.9.1
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - monitoring-network
      - default

  promtail:
    image: grafana/promtail:2.9.1
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
      - ./frontend/logs:/frontend/logs
      - ./backend/logs:/backend/logs
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - monitoring-network
      - default

  grafana:
    image: grafana/grafana:10.1.4
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - monitoring-network
      - default

networks:
  monitoring-network:
    driver: bridge

volumes:
  loki-data:
  grafana-data: 