server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log

  - job_name: frontend
    static_configs:
      - targets:
          - localhost
        labels:
          job: frontend
          service: frontend
          __path__: /frontend/logs/*log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            path: path
            method: method
            status: status
            latency: latency
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          path:
          method:
          status:

  - job_name: backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend
          service: backend
          __path__: /backend/logs/*log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            path: path
            method: method
            status: status
            latency: latency
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          path:
          method:
          status:
